### ISSUE TITLE
publish the package to nuget.org

### ISSUE THREAD

**Issue by avoxm** [Microsoft/CSharpClient-for-Kafka#28]
Now that Kafkanet supports nuget it would be great to publish it to nuget.org

**Comment by riamandii** [comment]
Hello, we have no manpower to

**Comment by Krishna-Desiraju** [comment]
+1

**Comment by mhorstma** [comment]
We are in the process of making this happen.  Stay tuned.

**Comment by mhorstma** [comment]
The package publishing pipeline is now functional and I expect we'll be able to keep nuget.org updated with "official"/good releases as needed.  You can access the package here:  https://www.nuget.org/packages/Microsoft.CSharpClient-for-Kafka/
